welcome_text = 'Hi, I\'m a bot that can read the content of YouTube videos from the link. '
'Let\'s get started. Send me a link to a YouTube video so '
'I can tell you what it\'s about'
wait_before_start_again = 'Wait for the previous reference to be processed'
processing_text_from_video_has_started = 'Processing text from video has started'
generation_started = 'Generation has started'
wait_for_the_previous_text_to_be_processed = 'Wait for the previous text to be processed'
processed_GPT_text = '️‼️Processed GPT text‼️'
an_error_occurred_while_reading_the_text_please_try_again = 'An error occurred while reading the text. Please try again.'
video_content_on_youtube = '📺 Video content on YouTube 📺'
wait_for_the_previous_text_to_be_processed = 'Wait for the previous text to be processed'
click_the_button_to_generate_a_video_summary = 'Click the button to generate a video summary'
